version: '3.8'

services:
  web:
    image: fmacmahon/cloud-project-b-web:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - custom_network

  db:
    image: fmacmahon/cloud-project-b-db:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - custom_network

  ws:
    image: fmacmahon/cloud-project-b-ws:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - custom_network

networks:
  custom_network:
    driver: overlay
